#SHOW THE PREVIOUS EMPLOYEE'S SALARY BASED ON HIRE DATE IN EACH DEPARTMENT USING CTE AND WINDOW FUNCTION

WITH RES1 AS (
SELECT *,LAG(SAL) OVER(PARTITION BY DEPTNO ORDER BY HIREDATE ASC) AS SALARY_PREVIOUS FROM EMP
)
SELECT * FROM RES1;

