#SHOW THE PREVIOUS EMPLOYEE'S SALARY BASED ON HIRE DATE IN EACH DEPARTMENT USING CTE AND WINDOW FUNCTION.

WITH RES1 AS (
SELECT *,LAG(SAL) OVER(PARTITION BY DEPTNO ORDER BY HIREDATE ASC) AS SALARY_PREVIOUS FROM EMP
)
SELECT * FROM RES1;


#SHOW THE NEXT EMPLOYEE'S SALARY BASED ON HIRE DATE USING WINDOW FUNCTIONS.

SELECT *,LEAD(SAL) OVER(ORDER BY HIREDATE) AS SALARY_NEXT FROM EMP;

